model_params:
  name: 'VanillaVAE'
  in_channels: 3
  latent_dim: 128

exp_params:
  dataset: concrete-cracks
  data_path: "/cvhci/data/construction/Concrete-Cracks"
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: [3]
  max_epochs: 10

logging_params:
  save_dir: "/cvhci/temp/p21g3/PyTorch-VAE/logs/"
  name: "VanillaVAE"
  manual_seed: 1265
